# Generated by Django 2.2.14 on 2020-11-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoriales.Editorial')),
            ],
        ),
    ]
